
# ===================================================================
#　データベース接続設定 (外部TomcatのJNDIリソースを参照)
# ===================================================================
spring.datasource.jndi-name=java:comp/env/jdbc/gift_db

